name: 'userfetch Action'
description: 'GitHub Actions for userfetch'
author: 'aryan02420'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'terminal'
  color: 'yellow'
inputs:
  config:
    description: 'Path to config file'
    required: true
  svg:
    description: 'Path to output svg'
    required: true
